### ISSUE TITLE
PayPal payment issue

### ISSUE THREAD

**Issue by Imaginaerum** [Imaginaerum/magento2-language-fr-fr#1047]
![image](https://cloud.githubusercontent.com/assets/7314174/17208669/f097fce8-54b9-11e6-85af-5938609e484c.png)

**Comment by Imaginaerum** [comment]
To test please [download master zip](https://github.com/Imaginaerum/magento2-language-fr-fr/archive/master.zip)

**Comment by Imaginaerum** [comment]
It seem a magento bug (configuration ? compilation ?). Same problem into english language... Need test

**Comment by quienti** [comment]
Apparently, this is know : https://github.com/magento/magento2/issues/4785 ? But, this is just a problem with a missing column no ?

**Comment by Imaginaerum** [comment]
Magento bug. Solved in 2.1.1 release.
