### ISSUE TITLE
Traductions manquantes

### ISSUE THREAD

**Issue by quienti** [Imaginaerum/magento2-language-fr-fr#1062]
Bonjour,

J'ai trouvé ces traductions qui n'existent pas
`Are you sure you want to remove this item from your Compare Products list?`
et
`Are you sure you want to remove all items from your Compare Products list?`

Dans ce js situé ici : 
https://github.com/magento/magento2/blob/6ea7d2d85cded3fa0fbcf4e7aa0dcd4edbf568a6/app/code/Magento/Catalog/view/frontend/web/js/view/compare-products.js#L24
et
https://github.com/magento/magento2/blob/6ea7d2d85cded3fa0fbcf4e7aa0dcd4edbf568a6/app/code/Magento/Catalog/view/frontend/web/js/view/compare-products.js#L28

Voilà, merci !

**Comment by Imaginaerum** [comment]
L'extracteur qui fait des siennes ? je regarde pourquoi... Merci pour le retour.
