### ISSUE TITLE
traduction partielle du bo produit

### ISSUE THREAD

**Issue by ndevilder-atena** [Imaginaerum/magento2-language-fr-fr#1063]
bonjour, apres instalation, l'edition de produit en back office n est que partiellement traduite ... une solution ? j'ai deja pas mal cherché mais sans succes

**Comment by quienti** [comment]
Bonjour,

Pouvez-vous être plus précis ?
Par exemple, quel est votre version de Magento et du pack, qu'est ce qui n'est pas traduit ( un screen aiderais beaucoup ).

Merci

**Comment by ndevilder-atena** [comment]
magento 2.1
Imaginaerum-magento2-language-fr-fr-100.6.22-0-g93ce2c0

![bug](https://cloud.githubusercontent.com/assets/20189916/18555585/b243660a-7b68-11e6-98b8-6d29ae28e939.png)

**Comment by quienti** [comment]
Effectivement, après vérification, l'édition de produit, mais aussi d'autres pages comme les catégories ne sont pas entièrement traduite.

Je viens de vérifier dans le fihier .csv, et les traductions existent bien.
Il est fort possible que ça soit "encore" un bug de Magento.

Je vais regarder dans le code de Magento ou dans les "issues" si il n'y a pas une référence à ce problème.

(Sachant que de nouvelle correction a été effectué sur les tranductions dans la branch develop de Magento, surement corrigé pour la 2.2)

**Comment by ndevilder-atena** [comment]
merci de ton aide ... j'ai fais ce que j ai pu mais la je vois pas

**Comment by Imaginaerum** [comment]
Il s'agit d'attributs. Ils ne sont donc pas traduit par les csv. Ils sont traduisibles via la gestion des attributs.

**Comment by quienti** [comment]
Oui, je suis d'accord avec le fait que ça soit des attributs, mais je n'explique pas le fait que certains sont traduit et d'autres non

**Comment by Imaginaerum** [comment]
Il y a eu des issues sur ceci:

- https://github.com/magento/magento2/issues/1980
- https://github.com/magento/magento2/issues/1983

**Comment by Imaginaerum** [comment]
Ceci ne provient donc pas du pack. Je clos cette issue.
