### ISSUE TITLE
Form validation messages not translated in Magento 2.1.1

### ISSUE THREAD

**Issue by pitangaweb** [Imaginaerum/magento2-language-fr-fr#1064]
On Magento 2.1.1, form validation messages on front-end stay in english:
`This is a required field`.
`Minimum of different classes of characters in password is 2. Classes of characters: Lower Case, Upper Case, Digits, Special Characters.`
`Please enter the same value again.`

**Comment by quienti** [comment]
Magento bug, fixed in develop branch
https://github.com/magento/magento2/pull/5725/commits/3109c8e96bcd08041f558be65a2a4e3d213d22a4

**Comment by Imaginaerum** [comment]
Thanks Quienti :)
It's Magento issue. I close it.
