### ISSUE TITLE
Request #87141c0

### ISSUE THREAD

**Issue by Fairlight60** [Imaginaerum/magento2-language-fr-fr#1065]
Original: "You already have an account with us. Sign in or continue as guest."

Your request: "Vous possédez déjà un compte. Connectez-vous ou continuez en tant qu'invité."
(Faute dans la ligne actuelle : "continuer" -> "continuez")

**Comment by Fairlight60** [comment]
Nevermind, just submitted this fix in a pull request.

**Comment by Imaginaerum** [comment]
Thanks a lot :)
