### ISSUE TITLE
Shipped = "Expédié" et non "Livré"

### ISSUE THREAD

**Issue by DogSports** [Imaginaerum/magento2-language-fr-fr#1077]
Shipped,Expédié
"Shipped By","Expédié par"
"Shipped or billed on:","Expédié ou facturé le :"
"Ship to:","Expédié à :"
"Ship to Applicable Countries","Expédier dans les pays applicables"
"Ship to Multiple Addresses","Expédier à plusieurs adresses"
"Ship to Specific Countries","Expédier dans des pays spécifiques"
"Ship to different address","Expédier à une autre adresse"
"Ship to this address","Expédier à cette adresse"
"Qty Shipped","Qté expédiée"
"Ship To","Expédié à"
"Ship To:","Expédié à :"
"Your %store_name order has shipped","Votre commande %store_name a été expédiée"

**Comment by Imaginaerum** [comment]
Merci pour le retour. Je traite ceci au plus vite.
