### ISSUE TITLE
Erreur composant

### ISSUE THREAD

**Issue by magegirl** [Imaginaerum/magento2-language-fr-fr#1078]
Bonjour,
Lorsque j'essaye d'aller sur le component manager  setup/#/component-grid, j'ai cette erreur : Couldn't get available versions for package imaginaerum/magento2-language-fr-fr

**Comment by magegirl** [comment]
up please

**Comment by quienti** [comment]
Bonjour,

Pouvez-vous donner plus d'info pour que je puisse peut-être vous aider ?
Comme la version de Magento, du module, mode d'installation, etc...

Ce problème n'est pas reproductible pour moi sous Magento 2.1.3, module 100.6.23 avec installation via le composer

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/21799480/bc5352ce-d719-11e6-8bb5-0e5ced1cd731.jpg)

**Comment by magegirl** [comment]
Bonjour,
le magento est en 2.1.3. J'ai trouvé un correctif sur la branche develop de magento qu'ils vont bientôt mettre en prod j'imagine.
