### ISSUE TITLE
Petite erreur côté emails

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [Imaginaerum/magento2-language-fr-fr#1100]
Bonjour,
Pour l'email d'expédition j'ai pu voir qu'on avait à la ligne 8750 : 
"Your %store_name order has shipped","Votre commande %store_name a été livrée"
au lieu de 
"Your %store_name order has shipped","Votre commande %store_name a été expédiée"
Merci pour la traduction
David

**Comment by Imaginaerum** [comment]
Fixé. Merci pour votre aide :)
