### ISSUE TITLE
passage à la langue anglaise lorsque l'on clique sur "tableau de bord"

### ISSUE THREAD

**Issue by elroliv** [Imaginaerum/magento2-language-fr-fr#1101]
Bonjour,

Tout d'abord, félicitation pour le pack de langue FR.

Je viens d'installer pour la première fois en local magento. 
Les taches cron ne sont pas encore activées.

Lorsque je clique sur "tableau de bord", tout repasse en anglais.
Lorsque je clique sur "Products > Catalog", tout repasse en français.

Quelqu'un a le même problème ?
Merci

Magento ver. 2.0.14

**Comment by Imaginaerum** [comment]
Merci encore. C'est un problème de cache. Faites un flush du cache M2
