### ISSUE TITLE
No images or CSS after language pack installation.

### ISSUE THREAD

**Issue by konnexionca** [Imaginaerum/magento2-language-fr-fr#1102]
Hi, after installing the french language pack and switching language to french, I have this issue. It also happens in the backend.

![image](https://user-images.githubusercontent.com/25209139/27347530-e348d524-55be-11e7-99d5-cd5e7600b5dc.png)
![image](https://user-images.githubusercontent.com/25209139/27347592-14c2c3da-55bf-11e7-976e-4f5da2b57858.png)

Any idea what is the problem?

**Comment by Imaginaerum** [comment]
You have compilation problem. Please re-compile M2.
