### ISSUE TITLE
Projet toujours actif ?

### ISSUE THREAD

**Issue by angelflo** [Imaginaerum/magento2-language-fr-fr#1137]
Bonjour,
Pouvez-vous me dire si vous continuez à maintenir cette traduction ?
Ne trouvant aucune information concernant la compatibilité avec magento 2.2.2 (ni magento 2.2.1) et plus de mise à jour depuis maintenant 8 mois, j'aimerai savoir si vous avez abandonné le projet ou si une nouvelle release est prévue sous peu.
Merci d'avance

**Comment by Imaginaerum** [comment]
Le projet n'est pas abandonné. Mais tout est pris sur mon temps libre et à titre gratuit. C'est parfois compliqué de maintenir ce type de projets. Donc non le projet n'est pas abandonné. Et il sera maintenu plus régulièrement. Cependant la version 2 de Magento a pas mal évolué. J'ai du écrire mon propre extracteur car celui natif n'était pas fiable. J'ai donc volontairement laissé Magento 2 "mûrir" un peu plus.

**Comment by angelflo** [comment]
Bonjour et merci pour la réponse.
1/ Avez-vous une prévision de date de sortie estimée pour la traduction Magento 2.2.2 ?
2/ Y a t'il moyen de vous aider pour la traduction .... genre se découper le travail ?
3/ Merci beaucoup de contribuer gratuitement à cette traduction. Je ne manquerai pas vous faire un don pour ce travail remarquable si une version Magento 2.2.2 voit le jour en espérant que les autres utilisateurs feront de même.

**Comment by sl02** [comment]
@Imaginaerum, nous avons exactement le même questionnement que @angelflo.

Nous avons aussi un besoin pour la traduction de Magento 2.2.2....nous pouvons définitivement aider aussi. Quel est l'état du projet?

**Comment by Imaginaerum** [comment]
Je vais recevoir de l'aide pour ce projet. Il est donc toujours actif ;)

**Comment by wget** [comment]
@Imaginaerum @angelflo Oui en effet, le projet est toujours plus actif et plus que jamais :) C'était [la release 4.7 de Mattermost cette semaine](https://github.com/wget/mattermost-localization-french-translation-rules) et ai donc été pris par le temps,, je m'occupe d'automatiser le projet de traduction de Magento très bientôt :)

@Imaginaerum Chouette de voir que vous fermez ces bugs reports :) C'était sur ma todo pour ce week-end :)

**Comment by Imaginaerum** [comment]
@wget merci encore pour l'aide ;)
