### ISSUE TITLE
/vendor/cbrunet/magento2-language-fr-ca/language.xml" is invalid: Element 'use', attribute 'package': [facet 'pattern'] 

### ISSUE THREAD

**Issue by jessicadelcueto** [Imaginaerum/magento2-language-fr-fr#1212]
The XML in file "C:/wamp64/www/magentotest/vendor/cbrunet/magento2-language-fr-ca/language.xml" is invalid: Element 'use', attribute 'package': [facet 'pattern'] The value 'magento2-language-fr-fr' is not accepted by the pattern '[a-zA-Z\-_]+'. Line: 21 Element 'use', attribute 'package': 'magento2-language-fr-fr' is not a valid value of the atomic type 'packageType'. Line: 21 Element 'use', attribute 'package': Warning: No precomputed value available, the value was either invalid or something strange happend. Line: 21 Verify the XML and try again.

**Comment by wget** [comment]
The problem seems to be from you side.
