### ISSUE TITLE
Afficher la méthide si elle n'est pas applicable

### ISSUE THREAD

**Issue by COTIGA** [Imaginaerum/magento2-language-fr-fr#16]
Bonjour

> Afficher la **méthide** si elle n'est pas applicable

Erreur trouvé dans Magasins => Ventes => Modes de livraison
Sinon good job,
Merci

**Comment by Imaginaerum** [comment]
Bonjour,

Merci beaucoup pour le retour.

La correction a été effectuée.

Cordialement.

Sylvain Kocet
