### ISSUE TITLE
Mini bug YesNo Backend

### ISSUE THREAD

**Issue by quienti** [Imaginaerum/magento2-language-fr-fr#18]
Bonjour

Fichier : fr_fr.module.magento_config.csv

Actuellement
`Yes => oui`
Devrait être
`Yes => Oui`

![sans titre 4](https://cloud.githubusercontent.com/assets/7326954/13947015/696895b2-f018-11e5-9185-840c9a3078a4.jpg)

**Comment by Imaginaerum** [comment]
Merci :) Corrigé ;)
