### ISSUE TITLE
Bug important

### ISSUE THREAD

**Issue by quienti** [Imaginaerum/magento2-language-fr-fr#20]
Bonjour,

Un gros problème avec les ' dans les scripts !

Par exemple :
Dans L'admin => Système => Gestion du Cache => Vider les caches

`Le cache peut contenir d'autres données. Êtes-vous sûr de vouloir le vider? `
L'apostrophe dans le texte ci-dessus empêche le fonctionnement correcte du script

Il doit y en avoir un peu partout des erreurs comme celui-ci mais je n'ai pas vraiment de liste exacte :/

Voilà, bon courage et merci ^^

**Comment by Imaginaerum** [comment]
Oui... Noramlement ils sont fixés par des methodes d'echappement. Mais le code Magento ne les utilisent pas tous le temps (voir: [mon pull request](https://github.com/magento/magento2/pull/3271/commits/4457c410b9ab2c9e64069de823a3b1fd5980faf0))
Je corrige... Merci :)

**Comment by Imaginaerum** [comment]
Possible de me dire si tout est ok ? merci :)

**Comment by quienti** [comment]
Ça fonctionne très bien, si je trouve le moindre soucis, je vous posterai "a issue" comme à chaque fois ;)

**Comment by Imaginaerum** [comment]
Merci encore pour l'aide précieuse :)

**Comment by quienti** [comment]
Avec grand plaisir ! ;)
