### ISSUE TITLE
Missing phrases on js - prefix : $t('[PHRASE]')

### ISSUE THREAD

**Issue by Imaginaerum** [Imaginaerum/magento2-language-fr-fr#21]
Missing translations...
"Adding..."
"Review & Payments"
...and more...

**Comment by quienti** [comment]
Bonjour,

Je sais très bien que les traductions dans les js ne fonctionne pas bien ou ne sont pas traduisible encore ^^

Mais il reste encore pas mal de traduction dans l'administration ^^ (Voir exemple ci-dessous)

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/14100690/9b9dd75a-f58f-11e5-9b5a-5df6804b2e5c.jpg)

La différence avec le frontend, c'est que dans l'administration, Magento utilise `$.mage.__('[PHRASE]')` , qui en théorie, fait pareil que `$t('[PHRASE]')`

**Comment by Imaginaerum** [comment]
Je vais regarder ca... Ce qui est sur c'est qu'on peut pas compter sur l'extracteur console. Je suis obliger d'enrichir le mien à chaque cas "tordu". À suivre...

**Comment by quienti** [comment]
Oui, malheureusement...

Mais de mémoire et d'après ce que j'ai vue, il y a eu pas mal de modifications encore à propos des traductions à la prochaine mise à jour de Magento
Possible que la prochaine mise à jour fonctionne mieux...

En tout cas, rien de grave ^^ Ce n'est que le backend ;)

**Comment by Imaginaerum** [comment]
J'ai même certains termes traduits qui ne sont pas actifs partout car pas "traduisible". Il faudrait identifier les fichiers qui les utilisent afin de faire des pull request vers le dépôt officiel de Magento 2.

**Comment by quienti** [comment]
Effectivement, ça serait une très bonne idée !

**Comment by quienti** [comment]
Bonjour,

Avez vous une liste des termes non "traduisible" pour que je puisse faire un `pull request`, sauf si vous avez déjà commencé à en faire un ^^ (Et aussi, si j'ai le temps libre ;) )

Merci d'avance
