### ISSUE TITLE
Manque traduction

### ISSUE THREAD

**Issue by quienti** [Imaginaerum/magento2-language-fr-fr#22]
Bonjour

Dans le checkout (paiement), j'ai bien vider mon cache de navigateur ainsi que celui de Magento et un redéploiement complet après la mise à jour Magento 2.0.4 ;)

![sans titre 4](https://cloud.githubusercontent.com/assets/7326954/14200682/d0f5e672-f7ec-11e5-8585-a63e22fbe9b5.jpg)

Les traductions se trouve dans ces fichiers : 
https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/web/js/view/payment.js#L56

https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/web/js/view/shipping.js#L86

Voilà ^^ Bon courage et merci d'avance

**Comment by Imaginaerum** [comment]
J'ai ajouté ce terme en traduction pour anticiper. Mais il n'est pas encore "traduisible". Un pull request a été fait. Voir L explication ici (dernier post) https://github.com/Imaginaerum/magento2-language-fr-fr/pull/19

**Comment by Imaginaerum** [comment]
Il faut donc patcher en attendant que la release officielle soit disponible sur cette modif.

**Comment by quienti** [comment]
C'est vraiment bizarre, dans mes liens qui sont sur la branche de développement, il y a bien le `$t('Review & Payments')`

Et quand je viens de vérifier dans mon Magento 2.0.4, effectivement, il n'y a pas `$t('Review & Payments')`

Mouais ^^

**Comment by quienti** [comment]
https://github.com/magento/magento2/issues/3953

**Comment by Imaginaerum** [comment]
Cette modif n'est pas encore dans une release taggée. Mais uniquement dans la branche develop

**Comment by quienti** [comment]
Pourtant, quand je prends l'archive de la release, j'ai bien les modifications...

Je ne comprendrais vraiment jamais comment ils fonctionnent chez Magento ^^

**Comment by quienti** [comment]
Sachant que les codes php ont eu les corrections que j'attendais donc vraiment, je ne vois vraiment pas pourquoi...

**Comment by Imaginaerum** [comment]
La jeunesse du produit...

**Comment by Imaginaerum** [comment]
Je viens de mettre à jour le package. Je clos l'issue. Il faut attendre une maj Magento.
