### ISSUE TITLE
Liste d'enVies

### ISSUE THREAD

**Issue by quienti** [Imaginaerum/magento2-language-fr-fr#364]
Bonjour

`https://github.com/Imaginaerum/magento2-language-fr-fr/blob/master/fr_fr.module.magento_rss.csv#L58`

`https://github.com/Imaginaerum/magento2-language-fr-fr/blob/master/fr_fr.module.magento_rss.csv#L57`

Un mini soucis dans l'admin

Merci, et bon courage avec la liste d'issue qu'il y a ^^

**Comment by quienti** [comment]
Fix ici : https://github.com/Imaginaerum/magento2-language-fr-fr/commit/d6812b6e734b4ceba505ef289cf73913390d9fc1

**Comment by Imaginaerum** [comment]
Oui, il y a de quoi améliorer avec la liste d'issues ;) Mais ça ne peut qu'améliorer le pack. Je viens de faire une mise à jour de version. Ce qui permet de prendre déjà en compte de nombreuses corrections.
