### ISSUE TITLE
Traductions des titres des mails de commande (pour l'instant non traduits)

### ISSUE THREAD

**Issue by owebia** [Imaginaerum/magento2-language-fr-fr#476]
"Credit memo for your %store_name order","Avoir pour votre commande %store_name",module,Magento_Sales
"Invoice for your %store_name order","Facture pour votre commande %store_name",module,Magento_Sales
"Update to your %store_name credit memo","Mise à jour de votre avoir %store_name",module,Magento_Sales
"Update to your %store_name invoice","Mise à jour de votre facture %store_name",module,Magento_Sales
"Update to your %store_name order","Mise à jour de votre commande %store_name",module,Magento_Sales
"Update to your %store_name shipment","Mise à jour de votre envoi %store_name",module,Magento_Sales
"Your %store_name order confirmation","Votre confirmation de commande %store_name",module,Magento_Sales
"Your %store_name order has shipped","Votre commande %store_name a été expédiée",module,Magento_Sales

**Comment by Imaginaerum** [comment]
Pull request en attente...

**Comment by Imaginaerum** [comment]
Et voilà: https://github.com/magento/magento2/commit/ee4f29472d8da2fe4c37a90e6a521f770575e42f
