### ISSUE TITLE
Traduction des titres des mails utilisateur

### ISSUE THREAD

**Issue by owebia** [Imaginaerum/magento2-language-fr-fr#477]
Please confirm your %store_name account,Merci de confirmer votre compte %store_name,module,Magento_Customer
Reset your %store_name password,Réinitialiser votre mot de passe %store_name,module,Magento_Customer
Your %store_name password has been changed,Votre mot de passe %store_name a été modifié,module,Magento_Customer
%store_name Newsletter subscription confirmation,Confirmez votre abonnement à la newsletter %store_name,module,Magento_Newsletter
%store_name Newsletter subscription success,Abonnement à la newsletter %store_name,module,Magento_Newsletter
%store_name Newsletter unsubscription success,Désabonnement de la newsletter %store_name,module,Magento_Newsletter

**Comment by Imaginaerum** [comment]
J'ai ouvert les pull request suivants: https://github.com/magento/magento2/pulls/Imaginaerum

**Comment by owebia** [comment]
Merci

**Comment by sajidunnar** [comment]
Hello Guys
Can you share how u generate these csv in multiple files or having one file is good enough ?

**Comment by Imaginaerum** [comment]
I think multiple files is better for context...

e.g:

"My context","Mon contexte",Magento,Sale
"My context","Mon autre contexte",Magento,Catalog

I use my own dictionary generator tool. Actually, I create a new version.

**Comment by Imaginaerum** [comment]
https://github.com/magento/magento2/commit/ee4f29472d8da2fe4c37a90e6a521f770575e42f

**Comment by Imaginaerum** [comment]
C'est encore dans la branche develop... Et pas encore dans la 2.0.6...

**Comment by sajidunnar** [comment]
@Imaginaerum sorry this is not right place to ask question but I found you are the one of active open source project on M2 translation 
My translation file is not working for JS alerts notifications anything specific we need to do ?

**Comment by Imaginaerum** [comment]
Javascript havé some bugs with translation. For example: e-mail field. And some translations are not available into Magento. I test it

**Comment by sajidunnar** [comment]
Oh okay thanks for clarification let me try to debug it

**Comment by Imaginaerum** [comment]
Les sujets traduisibles sont dans la 2.1-rc1 de Magento 2

**Comment by Imaginaerum** [comment]
La nouvelle version du pack est en cours:

- nettoyages des termes "buggés"
- extracteur plus performant car de nombreux termes manquent encore
- nouveau site web avec partie communautaire

**Comment by Imaginaerum** [comment]
#b71a834

**Comment by Imaginaerum** [comment]
fixé dans le commit b71a834
