### ISSUE TITLE
Utiliser "boutique" plutôt que "magasin"

### ISSUE THREAD

**Issue by owebia** [Imaginaerum/magento2-language-fr-fr#621]
Utiliser "boutique" plutôt que "magasin" dans les traductions.
Le terme "boutique" est plus utilisé pour parler d'un commerce en ligne.

**Comment by Imaginaerum** [comment]
Oui, je suis d'accord... Mais la vue magasin est un terme plus usuel dans Magento. vue boutique me semble étrange... Comment pourrait-on traduire ? (ou laisser vue boutique...).
Le terme magasin est utilisé 133 fois dans la traduction.

**Comment by Imaginaerum** [comment]
PS: je fixe à la version 100.6.6 dans pour le moment sans tenir compte du terme magasin (qui sera modifié dans la 100.6.7)

**Comment by owebia** [comment]
Je suis d'accord pour réfléchir avant de prendre une décision définitive sur cette question.  
Faudrait-il dissocier les traductions ?
- store = boutique
- store view = vue magasin

Quelques chiffres intéressants:  
http://context2.reverso.net/info.php?langFrom=en&langTo=fr&q=store&langTot=en-fr  
store = magasin [3785] conserver [1624] stocker [1248] boutique [488]

Associé à "online":  
http://context2.reverso.net/info.php?q=online+store&langFrom=en&langTo=fr&langTot=en-fr  
online store = boutique en ligne [10] magasin en ligne [7]

Pour l'expression "store view", je n'ai pas trouvé de chiffres concluants.

**Comment by Imaginaerum** [comment]
Bonsoir,


   - store = boutique
   - store view = vue magasin

Me semble pas mal...

Dans Magento 1 on était habitué à magasin... Mais cassons les codes ! Je
m'en suis aperçu en passant de Gmail a inbox. C'est déroutant au début mais
apres on préfère.

Je valide donc. Confirmez moi si autre suggestion. Je modifie la semaine
prochaine.

Sylvain

Le vendredi 29 avril 2016, owebia <notifications@github.com> a écrit :

> Je suis d'accord pour réfléchir avant de prendre une décision définitive
> sur cette question.
>
> Faudrait-il dissocier les traductions ?
>
>    - store = boutique
>    - store view = vue magasin
>
> Quelques chiffres intéressants:
>
>
> http://context2.reverso.net/info.php?langFrom=en&langTo=fr&q=store&langTot=en-fr
>
> store = magasin [3785] conserver [1624] stocker [1248] boutique [488]
>
> Associé à "online":
>
>
> http://context2.reverso.net/info.php?q=online+store&langFrom=en&langTo=fr&langTot=en-fr
>
> online store = boutique en ligne [10] magasin en ligne [7]
>
> Pour l'expression "store view", je n'ai pas trouvé de chiffres concluants.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Imaginaerum/magento2-language-fr-fr/issues/621#issuecomment-215845759>
>


-- 
Sent from Gmail Mobile

**Comment by Imaginaerum** [comment]
Bonsoir,


   - store = boutique
   - store view = vue magasin

Me semble pas mal...

Dans Magento 1 on était habitué à magasin... Mais cassons les codes ! Je
m'en suis aperçu en passant de Gmail a inbox. C'est déroutant au début mais
apres on préfère.

Je valide donc. Confirmez moi si autre suggestion

Le vendredi 29 avril 2016, owebia <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> a écrit :

> Je suis d'accord pour réfléchir avant de prendre une décision définitive
> sur cette question.
>
> Faudrait-il dissocier les traductions ?
>
>    - store = boutique
>    - store view = vue magasin
>
> Quelques chiffres intéressants:
>
>
> http://context2.reverso.net/info.php?langFrom=en&langTo=fr&q=store&langTot=en-fr
>
> store = magasin [3785] conserver [1624] stocker [1248] boutique [488]
>
> Associé à "online":
>
>
> http://context2.reverso.net/info.php?q=online+store&langFrom=en&langTo=fr&langTot=en-fr
>
> online store = boutique en ligne [10] magasin en ligne [7]
>
> Pour l'expression "store view", je n'ai pas trouvé de chiffres concluants.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Imaginaerum/magento2-language-fr-fr/issues/621#issuecomment-215845759>
>


-- 
Sent from Gmail Mobile

**Comment by Imaginaerum** [comment]
Modification faite dans @43fe180
