### ISSUE TITLE
Emplacement non utuilisable

### ISSUE THREAD

**Issue by BlueWaveFr** [Imaginaerum/magento2-language-fr-fr#631]
Bonjour, suite à l'installation via la ligne de commande, la langue n'est pas prise en compte.
et si j'installe votre pack ailleurs, cela ne fonctionne pas.
Emplacement Root/vendor/magento/vendor/imaginaerum/magento2-language-fr-fr
 Où dois-je le déplacer pour que cela fonctionne ?
Magento 2.0.4

**Comment by Imaginaerum** [comment]
Bonjour,

Le dossier où peut se situer le pack et dans le dossier vendor et app/i18n

Donc ca donne via composer:

/dossier/vers/racine/*vendor/imaginaerum/magento2-language-fr-fr*

et manuellement:

/dossier/vers/racine/*app/i18n/imaginaerum/fr_fr*

En racine de ses dossiers on trouvera le fichier registration.php et tous
les autres fichiers du pack (pas de sous-dossier, sinon ca ne fonctionne
pas):

- /dossier/vers/racine/*vendor/*imaginaerum/magento2-language-*fr-fr/*registration.php
... (et tous les autres fichiers)
ou
- /dossier/vers/racine/*app/i18n/imaginaerum/fr_fr**/*registration.php ...
(et tous les autres fichiers)

Il faut aussi également vider les caches Magento,
et éventuellement les désactiver pendant les tests de développement. Le
mieux et de vider entièrement les caches (faire un flush plutôt qu'un
clean). En effet, si les caches ne sont pas entièrement vidés, le pack
n'est pas actif. Pour l'admin, il faut suivre la procédure d'installation
ici: http://imaginaerum.github.io/magento2-language-fr-fr/

N'hésitez pas à revenir vers moi.

**Comment by quienti** [comment]
Via commande fonctionne très bien, c'est ce que j'ai utilisé quand j'étais sous Magento 2.0.2
