### ISSUE TITLE
Add to cart n added

### ISSUE THREAD

**Issue by nmallepally** [Imaginaerum/magento2-language-fr-fr#633]
![adding n added](https://cloud.githubusercontent.com/assets/19605497/16081942/a232ecf8-3307-11e6-9b45-f6dba7b888ce.png)

Hello,

Then french language pack has been installed but when I click on add to cart in French, the loading part shows in English as (adding and added).
I am attaching the image for reference as well. 

Regards,
Navya

**Comment by Imaginaerum** [comment]
https://github.com/magento/magento2/issues/4181

**Comment by Imaginaerum** [comment]
Fixed on last pack version with Magento 2.1.0. Can you try ?

**Comment by Imaginaerum** [comment]
Same as #634
