### ISSUE TITLE
Where to add phrases and words in the French translation

### ISSUE THREAD

**Issue by GlobalOutsourcing** [Imaginaerum/magento2-language-fr-fr#635]
Hi,

First of all thanks very much for this package, your effort and work.

I have installed it and at the frontend when I switch the language, the "Welcome to" and the footer "Privacy and Cookie Policy" is not translated. Where do I add these phrases to translate please?

I have googled the questions but no luck.

Please help me with some direction.

Thanking you in advance.

**Comment by Imaginaerum** [comment]
Thanks a lot. You can change it on configuration (Welcome). And magento block (Privacy and cookie policy). This is not Magento translations.

**Comment by GlobalOutsourcing** [comment]
Thank you for your reply.

If in future I want to add new words and phrases then where do I add them to the list? I see there are various csv files in the folder, is it a particular one or any one of the csv files?

Apologies for the simple questions but would appreciate your help with some guidance.

Thanking you in advance for your ongoing help.

**Comment by Imaginaerum** [comment]
You can use language inheritance

See: [language inheritance](http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-i18n.html#m2devgde-xlate-inheritancework)
