### ISSUE TITLE
Request #10af7c2

### ISSUE THREAD

**Issue by AlashaHonore** [Imaginaerum/magento2-language-fr-fr#636]
**Original:** "Add configurable attributes to the current Attribute Set"
**Your request:** Ajouter un attribut configurable au groupe d'attribut actuel

**Original:** "Add this attribute to the list of column options in the product grid."
**Your request:** Ajouter cet attribut à la liste des options de colonne dans la grille des produits.

**Original:** "Add this attribute to the list of filter options in the product grid."
**Your request:** Ajouter cet attribut à la liste des options filtrables dans la grille des produits.

**Original:** "Add Up-Sell Products"
**Your request:** Ajouter des produits en ventes additionnelles.

**Original:** "Admin session lifetime must be greater than or equal to 60 seconds"
**Your request:** La durée de vie de la session admin doit être supérieure ou égale à 60 secondes

**Original:** "Admin session lifetime must be less than or equal to 31536000 seconds (one year)"
**Your request:** La durée de vie de la session admin doit être inférieure ou égale à 31536000 secondes (1 an)

**Original:** "All other open sessions for this account were terminated."
**Your request:** Toutes les autres sessions ouvertes pour ce compte sont terminées.

**Original:** "Allowed file types: jpeg, gif, png."
**Your request:** Types de fichiers autorisés : jpeg, gif, png.

**Original:** "Allowed file types: jpg, jpeg, gif, png. To optimize logo for high-resolution displays, upload an image that is 3x normal size and then specify 1x dimensions in the width/height fields below."
**Your request:** Types de fichiers autorisés : jpg, jpeg, gif, png. Pour optimiser l'affichage du logo en haute résolution, importez une image dont la taille est 3x plus grande et spécifiez les dimensions 1x dans les champs largeur/hauteur ci-dessous.

**Original:** "Allowed file types: png, gif, jpg, jpeg, svg."
**Your request:** Types de fichiers autorisés : png, gif, jpg, jpeg, svg.

**Comment by Nolwennig** [comment]
The translation: 

Original: "Add configurable attributes to the current Attribute Set"
Your request: Ajouter un attribut configurable au groupe d'attribut actuel

Can be confuse French user, because "jeu d'attribut" and "groupe d"attribut" are differents

The translation should be:

**Original:** "Add configurable attributes to the current Attribute Set"
**Your request:** Ajouter un attribut configurable au jeu d'attribut actuel
