### ISSUE TITLE
Soucis mise à jour

### ISSUE THREAD

**Issue by quienti** [Imaginaerum/magento2-language-fr-fr#637]
Bonjour,

Votre dernière mise à jour pour Magento 2.1 me pose un petit soucis ^^

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/16659539/c78fce66-446a-11e6-9455-3ea37b67f51e.jpg)

Votre version : v100.6.14
Version Magrnto : 2.1.0

P.S : Merci pour la mise à jour 2.1.0, je l'attendais avec impatience ;)

**Comment by Imaginaerum** [comment]
Bonjour,

Oui il y a un probléme... Il est apparu aprés. je dois retirer cette mise à
jour :(

2016-07-07 17:47 GMT+02:00 quienti <notifications@github.com>:

**Comment by quienti** [comment]
Aucun soucis, faite ce qu'il faut ;)

Bon courage !

**Comment by Imaginaerum** [comment]
Il faut que je fixe mes fichiers csv. J'ai un bug apparemment sur l'ecritiire des csv. Je suis en train de refondre le pack pour l’alléger. et supprimer les "erreurs de jeunesse" du pack

**Comment by agoeurysky** [comment]
Bonjour @Imaginaerum ,

J'ai le même problème suite à la mise à jour 2.1.
En attendant la version 100.6.14 compatible avec la 2.1, les dernières versions sont-elles 100% compatibles pour la 2.1 ?

Merci.

**Comment by Imaginaerum** [comment]
Apparemment il y a un soucis de lecture CSV. En php 5.4 ca fonctionne apparemment mais la 2.1.0 fonctionne en php 5.6 mini... Je n'ai pas pu tester complètement. Car pas encore eu le temps de creuser.
